plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'pl.allegro.tech.build.axion-release' version '1.21.2'
	id 'maven-publish'
}

scmVersion {
	tag {
		prefix.set('v')
	}
	snapshotCreator { version, position -> '' }
	versionCreator('simple')

	localOnly.set(true)
}

version = scmVersion.version

loom {
	splitEnvironmentSourceSets()

	mods {
		"more-pups" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

repositories {
	exclusiveContent {
		forRepository {
			maven {
				name = 'GeckoLib'
				url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
			}
		}
		filter { includeGroupAndSubgroups('com.geckolib') }
	}
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	implementation "com.geckolib:geckolib-fabric-26.3:5.5.7"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}